vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       photos:

           uri_prefix: /media/photos
           upload_destination: '%kernel.project_dir%/public/media/photos'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true

       factures: 

           uri_prefix: /media/factures
           upload_destination: '%kernel.project_dir%/public/media/factures'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true

       devis: 
       
           uri_prefix: /media/devis
           upload_destination: '%kernel.project_dir%/public/media/devis'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

           inject_on_load: true
           delete_on_update: true
           delete_on_remove: true